development:
  adapter: postgresql
  database: buyer_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  database: buyer_test
  pool: 5
  username: postgres
  password: password
  host: localhost
